# Generated by Django 4.1.7 on 2026-02-25 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id_snapshot', models.CharField(db_index=True, max_length=8)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DRAW', 'Draw')], default='IN_PROGRESS', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('score_delta', models.JSONField(blank=True, default=dict)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_histories', to='App.room')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_game_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='UserScoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-total_score', 'user__username'),
            },
        ),
        migrations.CreateModel(
            name='GameParticipantResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(db_index=True, max_length=150)),
                ('result', models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('DRAW', 'Draw')], default='DRAW', max_length=8)),
                ('score_delta', models.IntegerField(default=0)),
                ('total_score_after_game', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_results', to='App.gamehistory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_participant_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
                'unique_together': {('game_history', 'username_snapshot')},
            },
        ),
        migrations.CreateModel(
            name='GameOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('operation_type', models.CharField(max_length=64)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('state_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='App.gamehistory')),
            ],
            options={
                'ordering': ('sequence', 'id'),
                'unique_together': {('game_history', 'sequence')},
            },
        ),
    ]
